"""
Django settings for univhub project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$$2k7sq*)mh@c0%e!lot0nd2bmpdni-_l$isuna&-(-_-dzu%$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'university',
    'global_auth',
    'student',
    'sadmin.apps.SadminConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
FCM_APIKEY = "AIzaSyBH-HlJabtrthLccXJqqa2vi8krqPNrpL4 "

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'sadmin.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'univhub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'global_auth','static')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'univhub.wsgi.application'
LOGIN_REDIRECT_URL = '/'
EMAIL_USE_TLS = True
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # mail service smtp
EMAIL_HOST_USER = 'enishpaneru2017@gmail.com'  # email id
EMAIL_HOST_PASSWORD = 'newpw2017'  # password
EMAIL_PORT = 587

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'sqlite_local': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    },
    'mysql_local': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'unihubed_django',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'USER': 'root',
        'PASSWORD': '',
    },
    'mysql_local_migrated': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'unihubed_django',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'USER': 'root',
        'PASSWORD': '',
    },
    'mysql_go_daddy': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'unihubed_django',
        'HOST': '166.62.102.112',
        'PORT': '3306',
        'USER': 'unihubed_django',
        'PASSWORD': 'UnivhuB#$%@',
    }
}
# DATABASES['default'] = DATABASES['mysql_go_daddy']

DATABASES['default'] = DATABASES['mysql_local_migrated']
# DATABASES = {
#
# }

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

FCM_DJANGO_SETTINGS = {
    "FCM_SERVER_KEY": "AAAAFvdqJHo:APA91bFRUlD_N_qKNcvHg82z83JTpXdtsvEu8LWtNWg_WrVjE_K321huaYlf0IIzLzVqq0gk3YR6QfHk3a20aZu-FEhucG6VTbnYAxO7XPfP09zVKvuZL6eXI4BFUk8u2vJLl5SqmXuq ",
    "ONE_DEVICE_PER_USER": False,
    "DELETE_INACTIVE_DEVICES": False
}
# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kathmandu'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


