# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityBasicInfo',
            fields=[
                ('university_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sadmin.University')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'university_basic_info',
                'managed': False,
            },
            bases=('sadmin.university',),
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='receiver_id',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='sender_id',
            new_name='sender',
        ),
    ]
