# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-20 04:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='header',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='major',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ranking',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='requirementbysubject',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='requirements',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='subheader',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='submajor',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='uniaddress',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='uniaddressmapping',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='universities',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='universitycontent',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='universityrequirement',
            options={'managed': False},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
    ]
