# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-03 15:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0002_auto_20171003_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='Type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 3, 15, 14, 22, 214176)),
        ),
        migrations.AlterField(
            model_name='offeredclass',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 3, 15, 14, 22, 212174)),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='status',
            field=models.CharField(choices=[('Picked', 'Picked'), ('Scheduled', 'Scheduled'), ('Unpicked', 'Unpicked'), ('Pending', 'Pending')], default='Pending', max_length=9),
        ),
    ]
