# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-09 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0002_auto_20171009_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadeddocument',
            old_name='url',
            new_name='file',
        ),
    ]
