# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0002_auto_20170925_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='user',
        ),
        migrations.AlterField(
            model_name='pickup',
            name='status',
            field=models.CharField(choices=[('Unpicked', 'Unpicked'), ('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('Picked', 'Picked')], default='Pending', max_length=9),
        ),
    ]
