# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 11:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sadmin', '0002_auto_20170920_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultancyName', models.CharField(max_length=30)),
                ('pan_vat', models.CharField(max_length=20)),
                ('reg_no', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'adminProfile',
            },
        ),
        migrations.CreateModel(
            name='ApplyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'applytype',
            },
        ),
        migrations.CreateModel(
            name='counsellorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField()),
                ('address', models.CharField(max_length=20)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminid', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'counsellorProfile',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryname', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('districtname', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'district',
            },
        ),
        migrations.CreateModel(
            name='moderatorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField()),
                ('address', models.CharField(max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'moderatorProfile',
            },
        ),
        migrations.CreateModel(
            name='ProgramsOffered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programOffered', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'programsOffered',
            },
        ),
        migrations.AlterModelOptions(
            name='universityrequirement',
            options={},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='citizenship',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='passport',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='scholarship',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sub_major',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sadmin.SubMajor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='apply_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sadmin.Country'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='apply_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sadmin.ApplyType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sadmin.District'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sadmin.ProgramsOffered'),
            preserve_default=False,
        ),
    ]
