# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-04 12:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0002_auto_20171004_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 4, 12, 9, 16, 297216)),
        ),
        migrations.AlterField(
            model_name='offeredclass',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
