# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0003_auto_20170921_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='pickup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Pending', 'Pending'), ('Picked', 'Picked'), ('Unpicked', 'Unpicked')], default='Pending', max_length=9)),
            ],
            options={
                'db_table': 'pickup',
            },
        ),
    ]
