# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-21 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0003_document'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='document',
            table='Document',
        ),
    ]
