# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 16:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sadmin', '0003_auto_20171006_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sadmin.Offer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registered_offer',
            },
        ),
        migrations.RemoveField(
            model_name='offeredclass',
            name='scholarshippercent',
        ),
        migrations.RemoveField(
            model_name='registeredclass',
            name='offeredclass_id',
        ),
        migrations.AddField(
            model_name='registeredclass',
            name='offeredclass',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sadmin.OfferedClass'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='offeredclass',
            table='offered_class',
        ),
        migrations.AlterModelTable(
            name='offertype',
            table='offer_type',
        ),
        migrations.AlterModelTable(
            name='programsoffered',
            table='programs_offered',
        ),
        migrations.AlterModelTable(
            name='scheduledpickup',
            table='scheduled_pickup',
        ),
    ]
