# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-04 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0003_auto_20171004_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
