# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-04 11:44
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0003_auto_20171003_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'notification_type',
            },
        ),
        migrations.RemoveField(
            model_name='uploadeddocuments',
            name='url',
        ),
        migrations.AddField(
            model_name='notification',
            name='map_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='web_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadeddocuments',
            name='file',
            field=models.FileField(default=2323232, upload_to='documents/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offer',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 4, 11, 44, 3, 784745)),
        ),
        migrations.AlterField(
            model_name='offeredclass',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 4, 11, 44, 3, 784745)),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='status',
            field=models.CharField(choices=[('Picked', 'Picked'), ('Unpicked', 'Unpicked'), ('Pending', 'Pending'), ('Scheduled', 'Scheduled')], default='Pending', max_length=9),
        ),
    ]
