# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0003_auto_20170925_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offerinclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sadmin.OfferedClass'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sadmin.Universities'),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='status',
            field=models.CharField(choices=[('Picked', 'Picked'), ('Unpicked', 'Unpicked'), ('Scheduled', 'Scheduled'), ('Pending', 'Pending')], default='Pending', max_length=9),
        ),
    ]
