# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-08 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0004_auto_20171007_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='documentfor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sadmin.DocumentFor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='isblocked',
            field=models.BooleanField(default=False),
        ),
    ]
