# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0004_pickup'),
    ]

    operations = [
        migrations.CreateModel(
            name='documentsforpickup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentname', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'documentsforpickup',
            },
        ),
        migrations.AlterField(
            model_name='pickup',
            name='status',
            field=models.CharField(choices=[('Unpicked', 'Unpicked'), ('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('Picked', 'Picked')], default='Pending', max_length=9),
        ),
        migrations.AddField(
            model_name='documentsforpickup',
            name='pickupfor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sadmin.pickup'),
        ),
    ]
