# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 07:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0004_auto_20170925_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 25, 12, 45, 43, 556670)),
        ),
        migrations.AddField(
            model_name='offeredclass',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 25, 12, 45, 43, 554894)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discountpercent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='scholarshippercent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Pending', 'Pending'), ('Unpicked', 'Unpicked'), ('Picked', 'Picked')], default='Pending', max_length=9),
        ),
    ]
