# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-08 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0005_auto_20171008_1046'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='consultancy',
            table='consultancy',
        ),
    ]
