# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 08:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0005_auto_20170925_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='qualification',
            field=models.TextField(default='MBA in English'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 25, 14, 15, 38, 69174)),
        ),
        migrations.AlterField(
            model_name='offeredclass',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 25, 14, 15, 38, 67500)),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Unpicked', 'Unpicked'), ('Scheduled', 'Scheduled'), ('Picked', 'Picked')], default='Pending', max_length=9),
        ),
    ]
