# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 08:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0006_auto_20170925_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 25, 14, 16, 13, 659587)),
        ),
        migrations.AlterField(
            model_name='offeredclass',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 25, 14, 16, 13, 657687)),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('Picked', 'Picked'), ('Unpicked', 'Unpicked')], default='Pending', max_length=9),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='qualification',
            field=models.TextField(),
        ),
    ]
