# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0006_auto_20171008_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultancy',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='counselor',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moderatorprofile',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
