# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 11:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0007_auto_20170925_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='sub_major',
        ),
        migrations.AlterField(
            model_name='offer',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 25, 17, 9, 31, 692074)),
        ),
        migrations.AlterField(
            model_name='offeredclass',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 25, 17, 9, 31, 690239)),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='status',
            field=models.CharField(choices=[('Picked', 'Picked'), ('Unpicked', 'Unpicked'), ('Pending', 'Pending'), ('Scheduled', 'Scheduled')], default='Pending', max_length=9),
        ),
    ]
