# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0007_auto_20170923_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='status',
            field=models.CharField(choices=[('Unpicked', 'Unpicked'), ('Scheduled', 'Scheduled'), ('Picked', 'Picked'), ('Pending', 'Pending')], default='Pending', max_length=9),
        ),
    ]
