# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 04:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0008_auto_20170925_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offeredclass',
            old_name='tutorname',
            new_name='tutor',
        ),
        migrations.AlterField(
            model_name='offer',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 26, 10, 15, 38, 106909)),
        ),
        migrations.AlterField(
            model_name='offeredclass',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 26, 10, 15, 38, 105213)),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Unpicked', 'Unpicked'), ('Scheduled', 'Scheduled'), ('Picked', 'Picked')], default='Pending', max_length=9),
        ),
    ]
