# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0009_auto_20170923_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'documents',
            },
        ),
    ]
