# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0010_documents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='documents',
        ),
        migrations.AddField(
            model_name='pickup',
            name='doctype',
            field=models.CharField(choices=[('Offer Documents', 'Offer Documents'), ('Financial Documents', 'Financial Documents'), ('Test Documents', 'Test Documents')], default='Financial Documents', max_length=30),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='status',
            field=models.CharField(choices=[('Unpicked', 'Unpicked'), ('Scheduled', 'Scheduled'), ('Picked', 'Picked'), ('Pending', 'Pending')], default='Pending', max_length=9),
        ),
    ]
