# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0011_auto_20170923_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='doctype',
            field=models.CharField(choices=[('Offer Documents', 'Offer Documents'), ('Test Documents', 'Test Documents'), ('Financial Documents', 'Financial Documents')], default='Financial Documents', max_length=30),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='status',
            field=models.CharField(choices=[('Unpicked', 'Unpicked'), ('Picked', 'Picked'), ('Pending', 'Pending'), ('Scheduled', 'Scheduled')], default='Pending', max_length=9),
        ),
    ]
