# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0012_auto_20170923_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='doctype',
            field=models.CharField(choices=[('Offer Documents', 'Offer Documents'), ('Financial Documents', 'Financial Documents'), ('Test Documents', 'Test Documents')], default='Financial Documents', max_length=30),
        ),
    ]
