# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0013_auto_20170923_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='doctype',
            field=models.CharField(choices=[('Test Documents', 'Test Documents'), ('Financial Documents', 'Financial Documents'), ('Offer Documents', 'Offer Documents')], default='Financial Documents', max_length=30),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='status',
            field=models.CharField(choices=[('Picked', 'Picked'), ('Pending', 'Pending'), ('Unpicked', 'Unpicked'), ('Scheduled', 'Scheduled')], default='Pending', max_length=9),
        ),
    ]
