# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 08:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sadmin', '0014_auto_20170923_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='documenttype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'documenttype',
            },
        ),
        migrations.CreateModel(
            name='pickupdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'pickupdetails',
            },
        ),
        migrations.CreateModel(
            name='uploadeddocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docname', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=250)),
                ('doctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sadmin.documenttype')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'uploadeddocuments',
            },
        ),
        migrations.RemoveField(
            model_name='documentsforpickup',
            name='pickupfor',
        ),
        migrations.RemoveField(
            model_name='pickup',
            name='doctype',
        ),
        migrations.AlterField(
            model_name='pickup',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Unpicked', 'Unpicked'), ('Picked', 'Picked'), ('Pending', 'Pending')], default='Pending', max_length=9),
        ),
        migrations.DeleteModel(
            name='documentsforpickup',
        ),
        migrations.AddField(
            model_name='pickupdetails',
            name='documentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sadmin.uploadeddocuments'),
        ),
        migrations.AddField(
            model_name='pickupdetails',
            name='pickupid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sadmin.pickup'),
        ),
    ]
