# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-24 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0016_auto_20170923_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='status',
            field=models.CharField(choices=[('Unpicked', 'Unpicked'), ('Pending', 'Pending'), ('Picked', 'Picked'), ('Scheduled', 'Scheduled')], default='Pending', max_length=9),
        ),
    ]
