# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-10 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import university.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'header',
            },
        ),
        migrations.CreateModel(
            name='HighlightMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight', models.TextField(verbose_name=university.models.HighlightText)),
            ],
        ),
        migrations.CreateModel(
            name='HighlightText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'levels',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'major',
            },
        ),
        migrations.CreateModel(
            name='ProgramsOffered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programoffered', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'programs_offered',
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('ranking_type', models.CharField(blank=True, max_length=7, null=True)),
                ('type_reference_table', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ranking',
            },
        ),
        migrations.CreateModel(
            name='ReqMap',
            fields=[
                ('hash_id', models.IntegerField(primary_key=True, serialize=False)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.Levels')),
            ],
            options={
                'db_table': 'req_map',
            },
        ),
        migrations.CreateModel(
            name='RequirementBySubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_id', models.IntegerField()),
                ('requirement_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'requirement_by_subject',
            },
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'requirements',
            },
        ),
        migrations.CreateModel(
            name='SubHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'sub_header',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('sub_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='SubMajor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_major_name', models.CharField(blank=True, max_length=250, null=True)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.Major')),
            ],
            options={
                'db_table': 'sub_major',
            },
        ),
        migrations.CreateModel(
            name='SubReqByUniversity',
            fields=[
                ('r_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sub_req_by_uni',
            },
        ),
        migrations.CreateModel(
            name='UniAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=250)),
                ('street', models.CharField(blank=True, max_length=250, null=True)),
                ('zip_code', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'uni_address',
            },
        ),
        migrations.CreateModel(
            name='UniAddressMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.IntegerField(blank=True, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='university.UniAddress')),
            ],
            options={
                'db_table': 'uni_address_mapping',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_line', models.TextField()),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('web_url', models.TextField()),
            ],
            options={
                'db_table': 'universities',
            },
        ),
        migrations.CreateModel(
            name='UniversityContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.Header')),
                ('sub_header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='university.SubHeader')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.University')),
            ],
            options={
                'db_table': 'university_content',
            },
        ),
        migrations.CreateModel(
            name='UniversityRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_score', models.IntegerField(blank=True, null=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.Requirements')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.University')),
            ],
            options={
                'db_table': 'university_requirement',
            },
        ),
        migrations.AddField(
            model_name='uniaddressmapping',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.University'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='belongs_to',
            field=models.ForeignKey(db_column='belongs_to', on_delete=django.db.models.deletion.DO_NOTHING, to='university.SubMajor'),
        ),
        migrations.AddField(
            model_name='requirementbysubject',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.Requirements'),
        ),
        migrations.AddField(
            model_name='requirementbysubject',
            name='u',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.University'),
        ),
        migrations.AddField(
            model_name='reqmap',
            name='req',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.SubReqByUniversity'),
        ),
        migrations.AddField(
            model_name='reqmap',
            name='submajor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='university.SubMajor'),
        ),
        migrations.AddField(
            model_name='reqmap',
            name='u',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.University'),
        ),
        migrations.AddField(
            model_name='ranking',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='university.University'),
        ),
        migrations.AddField(
            model_name='highlightmap',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.University'),
        ),
    ]
