# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-12 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseItemDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.ManyToManyField(to='university.CourseItemDescription')),
            ],
        ),
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HighlightText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramsOffered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programoffered', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('type_reference_table', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RankingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_description', models.TextField(blank=True, null=True)),
                ('value', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequirementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('sub_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubMajor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubMajorEnglishRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.TextField(blank=True, default=None, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.RequirementType')),
            ],
        ),
        migrations.CreateModel(
            name='SubMajorEntryRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubMajorOtherExpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubMajorStartDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('submajor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.SubMajor')),
            ],
        ),
        migrations.CreateModel(
            name='SubMajorTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubReqByUniversity',
            fields=[
                ('r_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TitleText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_line', models.TextField(blank=True, default=None, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('web_url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=250)),
                ('street', models.CharField(blank=True, max_length=250, null=True)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
                ('is_main', models.BooleanField()),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.University')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityCourseScholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_url', models.TextField(blank=True, default=None, null=True)),
                ('deadline', models.TextField(blank=True, default=None, null=True)),
                ('amount', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityCourseScholarshipItemTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityCourseScholoarshipItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.UniversityCourseScholarshipItemTitle')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_score', models.IntegerField(blank=True, default=None, null=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.Requirement')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.University')),
            ],
        ),
        migrations.CreateModel(
            name='UniversitySubMajor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_time', models.TextField(blank=True, default=None, null=True)),
                ('cost_per_year', models.TextField(blank=True, default=None, null=True)),
                ('detail_link', models.TextField(blank=True, default=None, null=True)),
                ('requirement_for_nepali', models.TextField(blank=True, default=None, null=True)),
                ('admission_process', models.ManyToManyField(to='university.UniversityCourseScholoarshipItem')),
                ('detail', models.ManyToManyField(to='university.CourseItems')),
                ('english_requirement', models.ManyToManyField(to='university.SubMajorEnglishRequirement')),
                ('entry_requirement', models.ManyToManyField(to='university.SubMajorEntryRequirement')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.Level')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.Major')),
                ('other_expenses', models.ManyToManyField(to='university.SubMajorOtherExpenses')),
                ('scholarship_detail', models.ManyToManyField(to='university.UniversityCourseScholarship')),
                ('start_date', models.ManyToManyField(to='university.Dates')),
                ('submajor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='university.SubMajor')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.SubMajorTitle')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.University')),
            ],
        ),
        migrations.CreateModel(
            name='UniversitySubMajorTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='universitycoursescholarship',
            name='description',
            field=models.ManyToManyField(to='university.UniversityCourseScholoarshipItem'),
        ),
        migrations.AddField(
            model_name='submajorotherexpenses',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.UniversityCourseScholarshipItemTitle'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='belongs_to',
            field=models.ForeignKey(db_column='belongs_to', on_delete=django.db.models.deletion.DO_NOTHING, to='university.SubMajor'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.RequirementType'),
        ),
        migrations.AddField(
            model_name='ranking',
            name='ranking_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='university.RankingType'),
        ),
        migrations.AddField(
            model_name='ranking',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='university.University'),
        ),
        migrations.AddField(
            model_name='highlighttext',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.University'),
        ),
        migrations.AddField(
            model_name='detail',
            name='header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='header', to='university.TitleText'),
        ),
        migrations.AddField(
            model_name='detail',
            name='sub_header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_header', to='university.TitleText'),
        ),
        migrations.AddField(
            model_name='detail',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.University'),
        ),
        migrations.AddField(
            model_name='courseitems',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.UniversitySubMajorTopic'),
        ),
    ]
